version: '3.8'

services:
  redisjson:
    image: redis/redis-stack:latest
    container_name: redisjson
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redisearch-data:/data

volumes:
  redisearch-data: